-- AlterTable
ALTER TABLE "Apartado" ADD COLUMN "fxRate" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION,
ADD COLUMN "taxVes" DOUBLE PRECISION,
ADD COLUMN "totalVes" DOUBLE PRECISION,
ADD COLUMN "initialPaymentVes" DOUBLE PRECISION,
ADD COLUMN "totalPaidVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ApartadoItem" ADD COLUMN "unitPriceVes" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ApartadoPayment" ADD COLUMN "amountVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "CashMovement" ADD COLUMN "amountVes" DOUBLE PRECISION,
ADD COLUMN "fxRate" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "CashRegister" ADD COLUMN "fxRate" DOUBLE PRECISION,
ADD COLUMN "baseAmountVes" DOUBLE PRECISION,
ADD COLUMN "expectedTotalVes" DOUBLE PRECISION,
ADD COLUMN "countedTotalVes" DOUBLE PRECISION,
ADD COLUMN "differenceVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN "fxRate" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION,
ADD COLUMN "taxVes" DOUBLE PRECISION,
ADD COLUMN "totalVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Purchase" ADD COLUMN "fxRate" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION,
ADD COLUMN "taxVes" DOUBLE PRECISION,
ADD COLUMN "totalVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PurchaseItem" ADD COLUMN "unitPriceVes" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sale" ADD COLUMN "fxRate" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION,
ADD COLUMN "taxVes" DOUBLE PRECISION,
ADD COLUMN "totalVes" DOUBLE PRECISION,
ADD COLUMN "receivedAmountVes" DOUBLE PRECISION,
ADD COLUMN "changeAmountVes" DOUBLE PRECISION,
ADD COLUMN "refundAmountVes" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN "unitPriceVes" DOUBLE PRECISION,
ADD COLUMN "subtotalVes" DOUBLE PRECISION;